function(ctorch_add_test target)
  cmake_parse_arguments(ARG "" "" "SOURCES;LIBS" ${ARGN})
  add_executable(${target} ${ARG_SOURCES})
  target_link_libraries(${target} PRIVATE GTest::gtest_main ${ARG_LIBS})
  target_compile_options(${target} PRIVATE ${CTORCH_WARNINGS})
  include(GoogleTest)
  gtest_discover_tests(${target})
endfunction()
